# Generated by Django 3.1.6 on 2021-07-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=50)),
                ('eventDescription', models.TextField()),
                ('eventCategory', models.CharField(choices=[('Seminars', 'Seminars'), ('Conferences', 'Conferences'), ('Trade Shows', 'Trade Shows'), ('Workshops', 'Workshops')], max_length=100)),
                ('eventLocation', models.CharField(max_length=100)),
                ('eventStart', models.CharField(max_length=100)),
                ('eventEnd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestRole',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('setAsOrganizer', models.BooleanField(default=False)),
                ('setAsAdministrator', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('requestEventID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizerID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.organizer'),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
