# Generated by Django 3.2.5 on 2021-07-06 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=50)),
                ('eventDescription', models.TextField()),
                ('eventCategory', models.CharField(choices=[('Seminars', 'Seminars'), ('Conferences', 'Conferences'), ('Trade Shows', 'Trade Shows'), ('Workshops', 'Workshops')], max_length=100)),
                ('eventLocation', models.CharField(max_length=100)),
                ('eventStart', models.DateField()),
                ('eventEnd', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
